#ifndef APOLLO11_EMBEDDED_PINBALL_NOUNS_H
#define APOLLO11_EMBEDDED_PINBALL_NOUNS_H

#include <stdint.h>

namespace pinball {

struct NounInfo {
  uint8_t noun;
  const char* name;
  const char* components;
};

constexpr NounInfo kNouns[] = {
    {1, "SPECIFY MACHINE ADDRESS FRACTIONAL", "COMP1,COMP2,COMP3"},
    {2, "SPECIFY MACHINE ADDRESS WHOLE", "COMP1,COMP2,COMP3"},
    {3, "SPECIFY MACHINE ADDRESS DEGREES", "COMP1,COMP2,COMP3"},
    {5, "ANGULAR ERROR/DIFFERENCE", "DEG"},
    {6, "OPTION CODE", "OCTAL,OCTAL"},
    {7, "ERASABLE WORD BIT MODIFICATION", "ECADR,MASK,SET/RESET"},
    {8, "ALARM DATA", "OCTAL,OCTAL,OCTAL"},
    {9, "ALARM CODES", "OCTAL,OCTAL,OCTAL"},
    {10, "CHANNEL TO BE SPECIFIED", "OCTAL"},
    {16, "TIME OF EVENT", "HOURS,MINUTES,SECONDS"},
    {17, "ASTRONAUT TOTAL ATTITUDE", "ROLL,PITCH,YAW"},
    {18, "AUTO MANEUVER BALL ANGLES", "ROLL,PITCH,YAW"},
    {20, "ICDU ANGLES", "ROLL,PITCH,YAW"},
    {21, "PIPAS", "X,Y,Z"},
    {22, "NEW ICDU ANGLES", "ROLL,PITCH,YAW"},
    {24, "DELTA TIME FOR AGC CLOCK", "HOURS,MINUTES,SECONDS"},
    {25, "CHECKLIST", "COMP1,COMP2,COMP3"},
    {26, "PRIORITY DELAY ADDRESS BBCON", "PRIO,ADRES,BBCON"},
    {27, "SELF TEST ON/OFF SWITCH", "SMODE"},
    {29, "LAUNCH AZIMUTH", "DEGREES"},
    {36, "TIME OF AGC CLOCK", "HOURS,MINUTES,SECONDS"},
    {40, "TIME FROM IGNITION/CUTOFF", "MIN/SEC,VG,DELTA-V"},
    {42, "APOGEE PERIGEE DELTA-V", "APOGEE,PERIGEE,DV"},
    {43, "LATITUDE LONGITUDE ALTITUDE", "LAT,LON,ALT"},
    {44, "ORBIT PARAMETER DISPLAY", "APOGEE,PERIGEE,TFF"},
    {47, "VEHICLE WEIGHT", "LEM MASS,CSM MASS"},
    {48, "PITCH/YAW TRIM", "PITCH,YAW"},
    {54, "RENDEZVOUS RADAR", "RANGE,RANGE RATE,THETA"},
    {62, "LM DESCENT MONITOR", "VEL/ALT,TIME,VEL"},
    {63, "LM DESCENT DISPLAY", "VEL,VEL,ALT"},
    {66, "LANDING RADAR", "ALTITUDE,POSITION"},
    {67, "LANDING RADAR VELOCITY", "VX,VY,VZ"},
    {68, "LANDING POINT DESIGNATOR", "POSITION,TIME,ALT"},
    {78, "RENDEZVOUS RADAR RANGE RATE", "RANGE,RANGE RATE"},
    {89, "RENDEZVOUS OUT OF PLANE", "ANGLE,ANGLE,POS"},
    {99, "MISSION-SPECIFIC TEST DISPLAY", "POS,VEL,ANGLE"},
};

inline const NounInfo* find(uint8_t noun) {
  for (uint8_t i = 0; i < sizeof(kNouns) / sizeof(kNouns[0]); ++i) {
    if (kNouns[i].noun == noun) {
      return &kNouns[i];
    }
  }

  return nullptr;
}

}  // namespace pinball

#endif
